version: "3"
services:
  selenium_hub:
    image: selenium/hub
    container_name: selenium_hub
    ports:
      - "4444:4444"
    networks:
      behavetestsnw: {}
  chromenode:
    image: selenium/node-chrome
    depends_on:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      behavetestsnw: {}
  firefoxnode:
    image: selenium/node-firefox
    depends_on:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      behavetestsnw: {}
  ui_tests:
    build: .
    command: -b chrome -g http://selenium_hub:4444/wd/hub --junit
    depends_on:
      - selenium_hub
      - chromenode
      - firefoxnode
    networks:
      behavetestsnw: {}
    volumes:
      - ./docker_outputs:/ui-integration-tests/outputs

networks:
  behavetestsnw:
    driver: bridge
