version: "3"
services:
  selenium_hub:
    image: selenium/hub
    container_name: selenium_hub
    ports:
      - "4444:4444"
    networks:
      behavetestsnw: {}
  chromenode:
    image: selenium/node-chrome
    depends_on:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      behavetestsnw: {}
  firefoxnode:
    image: selenium/node-firefox
    depends_on:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      behavetestsnw: {}
  ui_tests:
    build: .
    command: -t 15 chromenode:5555 -- behave
    depends_on:
      - selenium_hub
      - chromenode
      - firefoxnode
    networks:
      behavetestsnw: {}

networks:
  behavetestsnw:
    driver: bridge
